import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Gerardo M. | Marketing Analytics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* HEADER */}
      <section>
      <div className="grid grid-cols-1 md:grid-cols-2 my-5 mx-3">
        <div className="flex justify-end h-40 w-40 md:h-52 md:w-52 relative">
          <Image objectFit="contain" layout="fill" className="shadow-xl rounded-lg" src="https://imagesforpersonalsite.s3.us-west-2.amazonaws.com/header_image.png" alt="Photo of Gerardo M" />
        </div>
        <div className="mt-2 md:mt-0">
          <h1 className="font-thin text-5xl md:text-6xl text-black">hello i am</h1>
          <h2 className=" font-bold text-4xl md:text-5xl text-black">gerardo m.</h2>
          <div className="bg-pink-800">
            <p className=" text-white text-sm md:text-lg font-semibold">marketing analytics professional.</p>
          </div>
        </div>
      </div>
      </section>
    </div>
  )
}
