import Head from "next/head"
import Videocard from "../../../components/projects/youtube-dash/VideocardII";
import Stats from "../../../components/projects/youtube-dash/StatsII";
import TableofVideos from "../../../components/projects/youtube-dash/TableofVideosII";
import Graphs from "../../../components/projects/youtube-dash/Graphs";
import { useState } from "react";

const emptyData ={"items":{
  "0":{
    "most_views": {"title": "","publishedAt": "","viewCount": 0,
        "likeCount": 0,"dislikeCount": 0,"commentCount": 0,"thumbnail": "https://via.placeholder.com/320x180.png?text=TBD",
        "link": "","id": ""},
    "less_views": {"title": "","publishedAt": "","viewCount": 0,
        "likeCount": 0,"dislikeCount": 0,"commentCount": 0,"thumbnail": "https://via.placeholder.com/320x180.png?text=TBD",
        "link": "","id": ""},
    "most_recent": {"title": "","publishedAt": "","viewCount": 0,
        "likeCount": 0,"dislikeCount": 0,"commentCount": 0,"thumbnail": "https://via.placeholder.com/320x180.png?text=TBD",
        "link": "","id": ""}
},
"1":{
  "dislikes" : 0,
  "likes" : 0,
  "comments" : 0,
  "total_time" : 0},
"2":{
  "views": [0] * 50,
  "dates" : ["2021-05-01"]*50,
  "title":["TBD"] * 50
},
"3":{},
"4":{},
"5":{
  "channel_name": "Wating for Channel Info.",
  "country": "",
  "channel_main_stats": {
      "viewCount": 0,
      "subscriberCount": 0,
      "hiddenSubscriberCount": false,
      "videoCount": 0
      }},
"6":[{
  "title":"",
  "publishedAt":"",
  "viewCount":"",
  "commentCount":"",
  "publishedAt":"",
  "video_id":"", 
  "likeCount":"", 
  "link":""
}]


}}


export default function index() {

    const [text, setText] = useState("")
    const [query, setQuery] = useState(emptyData['items']);

    const printOnScreen = async(e) =>{
      e.preventDefault();
      console.log(text)
      try{
        const res = await fetch(`https://api.gmarr.me/youtube_dash/${text.split("?").pop()}`);
        const data = await res.json();
        console.log(res)
        setQuery(data['items'])
  
      }catch(err){
          console.log(err)
      }
    };

    console.log("--->",query[2])
    const counntryflag = query[5]['country']

    return (
        <div className="bg-gray-200 py-1">
        <Head>
          <title>Youtube Dashboard</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
            <div className="flex items-center">
              <div className="m-5">
                <h1 className="text-2xl text-gray-800 font-extrabold">Youtube Dashboard</h1>
                <p className="text-lg text-gray-700">Check the main stats of your favorite Youtube channel.</p>
              </div>
              <form action="" onSubmit={printOnScreen} onChange={(e) => setText(e.target.value)}>
                <div className="bg-white shadow p-2 flex">
                      <input class="w-full rounded p-2 text-gray-800 focus:outline-none focus:ring focus:border-blue-300" type="text" placeholder="Paste video URL." />
                      <button class="bg-red-400 hover:bg-red-300 rounded text-white p-2 pl-4 pr-4">
                              <p class="font-semibold text-xs">Search</p>
                      </button>
                </div>
              </form>
            </div>
            <div>
              <div className="text-2xl font-extrabold"><h1></h1></div>
              <div className="flex ml-5 items-center">
                <h1 className="text-xl text-gray-800 font-bold">Channel Title: <span className="text-xl text-gray-800 font-medium">{query[5]["channel_name"]}</span></h1>
                <img title={query[5]['country']} className="ml-3" src={`https://www.countryflags.io/${counntryflag}/flat/32.png`}></img>
              </div>
              <div className="grid lg:grid-cols-7 md:grid-cols-3 grid-cols-2 gap-1 m-5">
                <Stats
                  title="Subscribers"
                  data={parseInt(query[5]['channel_main_stats']['subscriberCount']).toLocaleString("en-US")}
                />
                <Stats
                  title="Published Videos"
                  data={parseInt(query[5]['channel_main_stats']['videoCount']).toLocaleString("en-US")}
                />
                <Stats
                  title="Total Views"
                  data={parseInt(query[5]['channel_main_stats']['viewCount']).toLocaleString("en-US")}
                  text="(Last 1,000 videos)"
                />
                <Stats
                  title="Total Likes"
                  data={query[1]['likes'].toLocaleString("en-US")}
                  text="(Last 1,000 videos)"
                />
                <Stats
                  title="Total Dislikes"
                  data={query[1]['dislikes'].toLocaleString("en-US")}
                  text="(Last 1,000 videos)"
                />
                <Stats
                  title="Total Comments"
                  data={query[1]['comments'].toLocaleString("en-US")}
                  text="(Last 1,000 videos)"
                />
                <Stats
                  title="Total Hours of Content"
                  data={Math.ceil(query[1]['total_time'].toLocaleString("en-US"))}
                  text="(Last 1,000 videos)"
                />
              </div>
            </div>
            <div className="grid md:grid-cols-2 lg:grid-cols-3 grid-cols-1 gap-4 m-5">
              {/* Video with the most views */}
              <Videocard 
                status="Most Recent Video" 
                title={query[0]['most_recent']['title']}
                img={query[0]['most_recent']['thumbnail']}
                views={query[0]['most_recent']["viewCount"].toLocaleString('en-US')}
                likes={query[0]['most_recent']["likeCount"].toLocaleString('en-US')}
                comments={query[0]['most_recent']["commentCount"].toLocaleString('en-US')}
                link={query[0]['most_recent']["link"]}
                published = {query[0]['most_recent']["publishedAt"]}
              />
              {/* Video with the most views */}
              <Videocard 
                status="Most Watched" 
                title={query[0]['most_views']['title']}
                img={query[0]['most_views']['thumbnail']}
                views={query[0]['most_views']["viewCount"].toLocaleString('en-US')}
                likes={query[0]['most_views']["likeCount"].toLocaleString('en-US')}
                comments={query[0]['most_views']["commentCount"].toLocaleString('en-US')}
                link={query[0]['most_views']["link"]}
                published = {query[0]['most_views']["publishedAt"]}
              />
              {/* Video with the most views */}
              <Videocard 
                status="Less Watched" 
                title={query[0]['less_views']['title']}
                img={query[0]['less_views']['thumbnail']}
                views={query[0]['less_views']["viewCount"].toLocaleString('en-US')}
                likes={query[0]['less_views']["likeCount"].toLocaleString('en-US')}
                comments={query[0]['less_views']["commentCount"].toLocaleString('en-US')}
                link={query[0]['less_views']["link"]}
                published = {query[0]['less_views']["publishedAt"]}
              />
            </div>
            <div className="grid grid-cols-1 gap-4 lg:grid-cols-3 m-5">
            <div className="col-span-2">
              <div className="mt-1 mb-5">
                <h1 className="text-xl text-gray-800 font-bold">Main Stats.</h1>
              </div>
              <Graphs data={query[2]}/>
            </div>
              <div>
                <div className="mt-1 mb-5">
                  <h1 className="text-xl text-gray-800 font-bold">Last 10 videos of the channel. </h1>
                </div>
                <TableofVideos tableData={query[6]}/>
              </div>
            </div>
        </div>
    )
}
